### PR TITLE
Add migration to create user bio column if that doesn't exist

### LINKED ISSUE #18: Rename user bio database column
As per https://github.com/flarum/core/issues/1280, the bio database column is getting dropped before stable. This extension should add a migration that, if a bio column exists, renames it to biography (or something else); if a bio column doesn't exist, creates a new one called biography (or something else)

### PR DESCRIPTION
**Pull request by askvortsov1**
Fixes #18

### CODE REVIEW

**Comment by dsevillamartin** [comment]
Let's not merge this until we know for sure that the column will be dropped (https://github.com/flarum/core/issues/1280#issuecomment-650655900).

**Comment by clarkwinkelmann** [comment]
I agree with @datitisev we can wait.

Regarding the PR itself I'd make two migrations. First one renames the column if it exists. Second migration creates the column if it doesn't exist and delete it in down. That way one migration actually contains the name "add column x". Otherwise I find it a bit confusing that the "rename" migration actually also creates and deletes the column...

**Comment by askvortsov1** [comment]
Agreed! Although hopefully we decide to go with Charlie's proposal in core, I think that's much cleaner

**Comment by askvortsov1** [comment]
@datitisev @clarkwinkelmann I updated this to comply with our new core strategy

**Comment by clarkwinkelmann** [comment]
I would actually suggest to just name the migration `create_bio_column` and add a comment above the `hasColumn` check that says something like "Older forums will already have this column created by Flarum. New forums created with beta 14 onwards will not have this column"

And/or just link to https://github.com/flarum/core/issues/1280 but I don't think that's needed, as we can easily go from code to commit, commit to PR and find all the history of why it was done.

**Comment by askvortsov1** [comment]
Done!

**Comment by KyrneDev** [comment]
Merging in response to the Core issue merge.

**Pull request merged**
