### PR TITLE
limit bio length

### PR DESCRIPTION
**Pull request by 892768447**

### CODE REVIEW

**Comment by 892768447** [comment]
When users submit a large amount of content maliciously,

The page will be very slow

**Comment by luceos** [comment]
Both of your PR's have good intent, but execution lacks. Simply cutting off any user provided value without feedback would seriously piss me off as a user.

What would be required:

- limiting the table column - requires a migration
- creating a validator used in the controller or handler
- limiting input size on the bio field (which I suggest would be the first thing to do)

**Comment by 892768447** [comment]
Forgive me for the simple and rude way

**Comment by luceos** [comment]
Absolutely no harm done. I am in fact very happy about this effort, great job. Will look at any new PR as soon as they come in 👍

**Pull request closed without merging**
